Give the update hook a unique name. (#301)
* Give the update hook a unique name.

This prevents the following errors:

```
Error: UPGRADE FAILED: post-upgrade hooks failed: warning: Hook post-upgrade litmus/templates/post-upgrade-hook.yaml failed: jobs.batch "chaos-litmus-upgrade-agent-cp" already exists
```

and will produce a new job on each upgrade.

Signed-off-by: David Collom <david.collom@jetstack.io>

* Bumping to litmus chart to 2.15.7

Signed-off-by: David Collom <david.collom@jetstack.io>

Signed-off-by: David Collom <david.collom@jetstack.io>